"""Generate sql/schema_postgres.sql and docs/data_dictionary.md from the warehouse metadata.

    python scripts/export_schema_and_dictionary.py
"""
from __future__ import annotations

import sys
from pathlib import Path

ROOT = Path(__file__).resolve().parents[1]
sys.path.insert(0, str(ROOT / "src"))

from sqlalchemy.dialects import postgresql  # noqa: E402
from sqlalchemy.schema import CreateIndex, CreateTable  # noqa: E402

from traffic_pipeline import warehouse_schema as ws  # noqa: E402

ORDER = ws.ANALYTICS_TABLES + ws.AUDIT_TABLES


def export_sql() -> str:
    dialect = postgresql.dialect()
    parts = ["-- Generated by scripts/export_schema_and_dictionary.py - do not edit by hand.",
             "-- Target: PostgreSQL 16 + PostGIS 3", "CREATE EXTENSION IF NOT EXISTS postgis;", ""]
    for name in ORDER:
        table = ws.metadata.tables[name]
        parts.append(str(CreateTable(table).compile(dialect=dialect)).strip() + ";")
        for index in sorted(table.indexes, key=lambda i: i.name):
            parts.append(str(CreateIndex(index).compile(dialect=dialect)).strip() + ";")
        if table.comment:
            parts.append(f"COMMENT ON TABLE {name} IS '{table.comment}';")
        for col in table.columns:
            if col.comment:
                parts.append(f"COMMENT ON COLUMN {name}.{col.name} IS '{col.comment.replace(chr(39), chr(39) * 2)}';")
        parts.append("")
    parts += [
        "-- Spatial columns added after each load (see traffic_pipeline/load.py):",
        "ALTER TABLE fact_accident ADD COLUMN IF NOT EXISTS geom geometry(Point, 4326);",
        "CREATE INDEX IF NOT EXISTS ix_fact_accident_geom ON fact_accident USING GIST (geom);",
        "ALTER TABLE mart_location_hotspots ADD COLUMN IF NOT EXISTS geom geometry(Point, 4326);",
    ]
    return "\n".join(parts) + "\n"


GROUPS = [
    ("Dimensions", [n for n in ORDER if n.startswith("dim_")]),
    ("Facts", [n for n in ORDER if n.startswith("fact_")]),
    ("Accident mart / aggregates", [n for n in ORDER if n.startswith(("agg_", "mart_"))]),
    ("Model-ready table (input to Part 2)", ["ml_accident_features"]),
    ("Audit and data-quality tables", ws.AUDIT_TABLES),
]


def export_dictionary() -> str:
    lines = ["# Data dictionary", "",
             "Generated from `src/traffic_pipeline/warehouse_schema.py` by "
             "`scripts/export_schema_and_dictionary.py`. PK = primary key, FK = foreign key.", ""]
    for group, names in GROUPS:
        lines += [f"## {group}", ""]
        for name in names:
            table = ws.metadata.tables[name]
            lines += [f"### `{name}`", "", table.comment or "", "",
                      "| Column | Type | Key | Description |", "|---|---|---|---|"]
            for col in table.columns:
                key = "PK" if col.primary_key else ""
                if col.foreign_keys:
                    key = (key + " " if key else "") + "FK → " + ", ".join(fk.target_fullname for fk in col.foreign_keys)
                lines.append(f"| `{col.name}` | {col.type.compile(dialect=postgresql.dialect())} | {key} | "
                             f"{col.comment or ''} |")
            lines.append("")
    return "\n".join(lines)


if __name__ == "__main__":
    (ROOT / "sql").mkdir(exist_ok=True)
    (ROOT / "docs").mkdir(exist_ok=True)
    (ROOT / "sql" / "schema_postgres.sql").write_text(export_sql(), encoding="utf-8")
    (ROOT / "docs" / "data_dictionary.md").write_text(export_dictionary(), encoding="utf-8")
    print("wrote sql/schema_postgres.sql and docs/data_dictionary.md")
