-- Generated by scripts/export_schema_and_dictionary.py - do not edit by hand.
-- Target: PostgreSQL 16 + PostGIS 3
CREATE EXTENSION IF NOT EXISTS postgis;

CREATE TABLE dim_date (
	date_key INTEGER NOT NULL, 
	full_date DATE, 
	year INTEGER, 
	quarter INTEGER, 
	month INTEGER, 
	month_name VARCHAR(12), 
	day_of_month INTEGER, 
	weekday_num INTEGER, 
	weekday_name VARCHAR(10), 
	is_weekend BOOLEAN, 
	season VARCHAR(10), 
	PRIMARY KEY (date_key)
);
COMMENT ON TABLE dim_date IS 'Calendar dimension covering every day in the extracted period';
COMMENT ON COLUMN dim_date.date_key IS 'Surrogate key yyyymmdd';
COMMENT ON COLUMN dim_date.full_date IS 'Calendar date';
COMMENT ON COLUMN dim_date.year IS 'Calendar year';
COMMENT ON COLUMN dim_date.quarter IS 'Quarter 1-4';
COMMENT ON COLUMN dim_date.month IS 'Month number 1-12';
COMMENT ON COLUMN dim_date.month_name IS 'Month name';
COMMENT ON COLUMN dim_date.day_of_month IS 'Day of month';
COMMENT ON COLUMN dim_date.weekday_num IS 'ISO weekday, 1 = Monday ... 7 = Sunday';
COMMENT ON COLUMN dim_date.weekday_name IS 'Weekday name';
COMMENT ON COLUMN dim_date.is_weekend IS 'True for Saturday/Sunday';
COMMENT ON COLUMN dim_date.season IS 'Meteorological season (Winter = Dec-Feb)';

CREATE TABLE dim_time (
	hour_key INTEGER NOT NULL, 
	hour_label VARCHAR(5), 
	time_band VARCHAR(30), 
	is_peak_hour BOOLEAN, 
	PRIMARY KEY (hour_key)
);
COMMENT ON TABLE dim_time IS 'Hour-of-day dimension';
COMMENT ON COLUMN dim_time.hour_key IS 'Hour of day 0-23 (UK local time)';
COMMENT ON COLUMN dim_time.hour_label IS 'Hour as HH:00';
COMMENT ON COLUMN dim_time.time_band IS 'Night / morning peak / daytime / evening peak / late evening';
COMMENT ON COLUMN dim_time.is_peak_hour IS '07-09 or 16-18';

CREATE TABLE dim_location (
	location_key INTEGER NOT NULL, 
	police_force_code VARCHAR(10), 
	police_force_name VARCHAR(40), 
	nation VARCHAR(10), 
	local_authority_ons_district VARCHAR(12), 
	urban_rural_label VARCHAR(20), 
	weather_cell_id VARCHAR(16), 
	PRIMARY KEY (location_key)
);
COMMENT ON TABLE dim_location IS 'Location dimension (police force, local authority, urban/rural, weather cell)';
COMMENT ON COLUMN dim_location.location_key IS 'Surrogate key';
COMMENT ON COLUMN dim_location.police_force_code IS 'STATS19 police force code';
COMMENT ON COLUMN dim_location.police_force_name IS 'Police force name';
COMMENT ON COLUMN dim_location.nation IS 'England / Wales / Scotland (derived from police force)';
COMMENT ON COLUMN dim_location.local_authority_ons_district IS 'ONS local authority district code';
COMMENT ON COLUMN dim_location.urban_rural_label IS 'Urban / Rural / Unallocated';
COMMENT ON COLUMN dim_location.weather_cell_id IS 'Weather grid cell centre ''lat_lon'' used for the Open-Meteo join';

CREATE TABLE dim_road (
	road_key INTEGER NOT NULL, 
	first_road_class_label VARCHAR(20), 
	road_type_label VARCHAR(40), 
	speed_limit_label VARCHAR(20), 
	junction_detail_label VARCHAR(40), 
	junction_control_label VARCHAR(40), 
	PRIMARY KEY (road_key)
);
COMMENT ON TABLE dim_road IS 'Road dimension (junk dimension of road attributes)';
COMMENT ON COLUMN dim_road.road_key IS 'Surrogate key';
COMMENT ON COLUMN dim_road.first_road_class_label IS 'Motorway, A(M), A, B, C, Unclassified';
COMMENT ON COLUMN dim_road.road_type_label IS 'Roundabout, single/dual carriageway, slip road, ...';
COMMENT ON COLUMN dim_road.speed_limit_label IS 'Posted speed limit in mph (text, ''Unknown'' if invalid)';
COMMENT ON COLUMN dim_road.junction_detail_label IS 'Junction type at the collision site';
COMMENT ON COLUMN dim_road.junction_control_label IS 'Junction control (signals, give way, ...)';

CREATE TABLE dim_weather (
	weather_key INTEGER NOT NULL, 
	weather_conditions_label VARCHAR(40), 
	road_surface_label VARCHAR(30), 
	light_conditions_label VARCHAR(40), 
	temperature_band VARCHAR(20), 
	precipitation_band VARCHAR(30), 
	wind_band VARCHAR(30), 
	PRIMARY KEY (weather_key)
);
COMMENT ON TABLE dim_weather IS 'Weather and environment dimension (police-recorded + measured weather bands)';
COMMENT ON COLUMN dim_weather.weather_key IS 'Surrogate key';
COMMENT ON COLUMN dim_weather.weather_conditions_label IS 'Weather recorded by police (STATS19)';
COMMENT ON COLUMN dim_weather.road_surface_label IS 'Road surface condition (STATS19)';
COMMENT ON COLUMN dim_weather.light_conditions_label IS 'Light conditions (STATS19)';
COMMENT ON COLUMN dim_weather.temperature_band IS 'Open-Meteo temperature band at the collision hour';
COMMENT ON COLUMN dim_weather.precipitation_band IS 'Open-Meteo precipitation band at the collision hour';
COMMENT ON COLUMN dim_weather.wind_band IS 'Open-Meteo wind-speed band at the collision hour';

CREATE TABLE dim_severity (
	severity_key INTEGER NOT NULL, 
	severity_label VARCHAR(10), 
	is_ksi BOOLEAN, 
	severity_rank INTEGER, 
	PRIMARY KEY (severity_key)
);
COMMENT ON TABLE dim_severity IS 'Collision severity dimension';
COMMENT ON COLUMN dim_severity.severity_key IS '1 Fatal, 2 Serious, 3 Slight';
COMMENT ON COLUMN dim_severity.severity_label IS 'Severity label';
COMMENT ON COLUMN dim_severity.is_ksi IS 'Killed or seriously injured (Fatal or Serious)';
COMMENT ON COLUMN dim_severity.severity_rank IS '1 = most severe';

CREATE TABLE fact_accident (
	collision_index VARCHAR(20) NOT NULL, 
	date_key INTEGER, 
	hour_key INTEGER, 
	location_key INTEGER, 
	road_key INTEGER, 
	weather_key INTEGER, 
	severity_key INTEGER, 
	collision_datetime TIMESTAMP WITHOUT TIME ZONE, 
	latitude FLOAT, 
	longitude FLOAT, 
	lsoa_code VARCHAR(12), 
	number_of_vehicles INTEGER, 
	number_of_casualties INTEGER, 
	n_pedestrian_casualties INTEGER, 
	n_fatal_casualties INTEGER, 
	n_serious_casualties INTEGER, 
	n_child_casualties INTEGER, 
	involves_pedal_cycle BOOLEAN, 
	involves_motorcycle BOOLEAN, 
	involves_car BOOLEAN, 
	involves_bus BOOLEAN, 
	involves_goods_vehicle BOOLEAN, 
	mean_driver_age FLOAT, 
	youngest_driver_age FLOAT, 
	weather_matched BOOLEAN, 
	temperature_c FLOAT, 
	precipitation_mm FLOAT, 
	rain_mm FLOAT, 
	snowfall_cm FLOAT, 
	wind_speed_kmh FLOAT, 
	wind_gusts_kmh FLOAT, 
	cloud_cover_pct FLOAT, 
	humidity_pct FLOAT, 
	wmo_weather_code FLOAT, 
	police_attended_label VARCHAR(30), 
	PRIMARY KEY (collision_index), 
	FOREIGN KEY(date_key) REFERENCES dim_date (date_key), 
	FOREIGN KEY(hour_key) REFERENCES dim_time (hour_key), 
	FOREIGN KEY(location_key) REFERENCES dim_location (location_key), 
	FOREIGN KEY(road_key) REFERENCES dim_road (road_key), 
	FOREIGN KEY(weather_key) REFERENCES dim_weather (weather_key), 
	FOREIGN KEY(severity_key) REFERENCES dim_severity (severity_key)
);
CREATE INDEX ix_fact_accident_date ON fact_accident (date_key);
CREATE INDEX ix_fact_accident_location ON fact_accident (location_key);
CREATE INDEX ix_fact_accident_severity ON fact_accident (severity_key);
COMMENT ON TABLE fact_accident IS 'One row per reported road collision (grain: collision)';
COMMENT ON COLUMN fact_accident.collision_index IS 'DfT unique collision id';
COMMENT ON COLUMN fact_accident.date_key IS 'FK dim_date';
COMMENT ON COLUMN fact_accident.hour_key IS 'FK dim_time';
COMMENT ON COLUMN fact_accident.location_key IS 'FK dim_location';
COMMENT ON COLUMN fact_accident.road_key IS 'FK dim_road';
COMMENT ON COLUMN fact_accident.weather_key IS 'FK dim_weather';
COMMENT ON COLUMN fact_accident.severity_key IS 'FK dim_severity';
COMMENT ON COLUMN fact_accident.collision_datetime IS 'Local date and time of the collision';
COMMENT ON COLUMN fact_accident.latitude IS 'WGS84 latitude';
COMMENT ON COLUMN fact_accident.longitude IS 'WGS84 longitude';
COMMENT ON COLUMN fact_accident.lsoa_code IS 'Lower Super Output Area of the collision';
COMMENT ON COLUMN fact_accident.number_of_vehicles IS 'Vehicles involved';
COMMENT ON COLUMN fact_accident.number_of_casualties IS 'Casualties';
COMMENT ON COLUMN fact_accident.n_pedestrian_casualties IS 'Pedestrian casualties';
COMMENT ON COLUMN fact_accident.n_fatal_casualties IS 'Fatal casualties';
COMMENT ON COLUMN fact_accident.n_serious_casualties IS 'Seriously injured casualties';
COMMENT ON COLUMN fact_accident.n_child_casualties IS 'Casualties aged under 16';
COMMENT ON COLUMN fact_accident.involves_pedal_cycle IS 'At least one pedal cycle involved';
COMMENT ON COLUMN fact_accident.involves_motorcycle IS 'At least one motorcycle involved';
COMMENT ON COLUMN fact_accident.involves_car IS 'At least one car/taxi involved';
COMMENT ON COLUMN fact_accident.involves_bus IS 'At least one bus/minibus involved';
COMMENT ON COLUMN fact_accident.involves_goods_vehicle IS 'At least one goods vehicle involved';
COMMENT ON COLUMN fact_accident.mean_driver_age IS 'Mean age of drivers (known ages only)';
COMMENT ON COLUMN fact_accident.youngest_driver_age IS 'Youngest driver age';
COMMENT ON COLUMN fact_accident.weather_matched IS 'True when an Open-Meteo reading was joined';
COMMENT ON COLUMN fact_accident.temperature_c IS 'Air temperature at 2 m (C), Open-Meteo';
COMMENT ON COLUMN fact_accident.precipitation_mm IS 'Precipitation in the hour (mm), Open-Meteo';
COMMENT ON COLUMN fact_accident.rain_mm IS 'Rain in the hour (mm), Open-Meteo';
COMMENT ON COLUMN fact_accident.snowfall_cm IS 'Snowfall in the hour (cm), Open-Meteo';
COMMENT ON COLUMN fact_accident.wind_speed_kmh IS 'Wind speed at 10 m (km/h), Open-Meteo';
COMMENT ON COLUMN fact_accident.wind_gusts_kmh IS 'Wind gusts at 10 m (km/h), Open-Meteo';
COMMENT ON COLUMN fact_accident.cloud_cover_pct IS 'Cloud cover (%), Open-Meteo';
COMMENT ON COLUMN fact_accident.humidity_pct IS 'Relative humidity at 2 m (%), Open-Meteo';
COMMENT ON COLUMN fact_accident.wmo_weather_code IS 'WMO weather code, Open-Meteo';
COMMENT ON COLUMN fact_accident.police_attended_label IS 'Whether a police officer attended the scene';

CREATE TABLE fact_vehicle (
	collision_index VARCHAR(20) NOT NULL, 
	vehicle_reference INTEGER NOT NULL, 
	date_key INTEGER, 
	collision_severity_key INTEGER, 
	vehicle_type VARCHAR(40), 
	vehicle_category VARCHAR(30), 
	sex_of_driver VARCHAR(20), 
	age_of_driver FLOAT, 
	age_band_of_driver VARCHAR(20), 
	engine_capacity_cc FLOAT, 
	age_of_vehicle FLOAT, 
	PRIMARY KEY (collision_index, vehicle_reference), 
	FOREIGN KEY(collision_index) REFERENCES fact_accident (collision_index), 
	FOREIGN KEY(date_key) REFERENCES dim_date (date_key), 
	FOREIGN KEY(collision_severity_key) REFERENCES dim_severity (severity_key)
);
COMMENT ON TABLE fact_vehicle IS 'One row per vehicle involved in a collision';
COMMENT ON COLUMN fact_vehicle.collision_index IS 'FK fact_accident';
COMMENT ON COLUMN fact_vehicle.vehicle_reference IS 'Vehicle number within the collision';
COMMENT ON COLUMN fact_vehicle.date_key IS 'FK dim_date';
COMMENT ON COLUMN fact_vehicle.collision_severity_key IS 'Severity of the collision';
COMMENT ON COLUMN fact_vehicle.vehicle_type IS 'Vehicle type label';
COMMENT ON COLUMN fact_vehicle.vehicle_category IS 'Grouped vehicle type';
COMMENT ON COLUMN fact_vehicle.sex_of_driver IS 'Driver sex';
COMMENT ON COLUMN fact_vehicle.age_of_driver IS 'Driver age (null if unknown/invalid)';
COMMENT ON COLUMN fact_vehicle.age_band_of_driver IS 'Driver age band';
COMMENT ON COLUMN fact_vehicle.engine_capacity_cc IS 'Engine capacity (cc)';
COMMENT ON COLUMN fact_vehicle.age_of_vehicle IS 'Vehicle age (years)';

CREATE TABLE fact_casualty (
	collision_index VARCHAR(20) NOT NULL, 
	casualty_reference INTEGER NOT NULL, 
	vehicle_reference INTEGER, 
	date_key INTEGER, 
	casualty_severity_key INTEGER, 
	casualty_severity VARCHAR(10), 
	casualty_class VARCHAR(30), 
	casualty_type_group VARCHAR(30), 
	sex_of_casualty VARCHAR(20), 
	age_of_casualty FLOAT, 
	age_band_of_casualty VARCHAR(20), 
	PRIMARY KEY (collision_index, casualty_reference), 
	FOREIGN KEY(collision_index) REFERENCES fact_accident (collision_index), 
	FOREIGN KEY(date_key) REFERENCES dim_date (date_key), 
	FOREIGN KEY(casualty_severity_key) REFERENCES dim_severity (severity_key)
);
COMMENT ON TABLE fact_casualty IS 'One row per casualty';
COMMENT ON COLUMN fact_casualty.collision_index IS 'FK fact_accident';
COMMENT ON COLUMN fact_casualty.casualty_reference IS 'Casualty number within the collision';
COMMENT ON COLUMN fact_casualty.vehicle_reference IS 'Vehicle the casualty was in / hit by';
COMMENT ON COLUMN fact_casualty.date_key IS 'FK dim_date';
COMMENT ON COLUMN fact_casualty.casualty_severity_key IS 'FK dim_severity';
COMMENT ON COLUMN fact_casualty.casualty_severity IS 'Casualty severity label';
COMMENT ON COLUMN fact_casualty.casualty_class IS 'Driver or rider / Passenger / Pedestrian';
COMMENT ON COLUMN fact_casualty.casualty_type_group IS 'Pedestrian or road-user group of the casualty';
COMMENT ON COLUMN fact_casualty.sex_of_casualty IS 'Casualty sex';
COMMENT ON COLUMN fact_casualty.age_of_casualty IS 'Casualty age';
COMMENT ON COLUMN fact_casualty.age_band_of_casualty IS 'Casualty age band';

CREATE TABLE agg_accidents_by_hour (
	year INTEGER, 
	weekday_num INTEGER, 
	weekday_name VARCHAR(10), 
	hour_key INTEGER, 
	accidents INTEGER, 
	fatal INTEGER, 
	serious INTEGER, 
	slight INTEGER, 
	casualties INTEGER, 
	ksi_rate FLOAT
);
COMMENT ON TABLE agg_accidents_by_hour IS 'Collisions by year, weekday and hour';
COMMENT ON COLUMN agg_accidents_by_hour.year IS 'Year';
COMMENT ON COLUMN agg_accidents_by_hour.weekday_num IS '1 = Monday';
COMMENT ON COLUMN agg_accidents_by_hour.weekday_name IS 'Weekday';
COMMENT ON COLUMN agg_accidents_by_hour.hour_key IS 'Hour 0-23';
COMMENT ON COLUMN agg_accidents_by_hour.accidents IS 'Number of collisions';
COMMENT ON COLUMN agg_accidents_by_hour.fatal IS 'Fatal collisions';
COMMENT ON COLUMN agg_accidents_by_hour.serious IS 'Serious collisions';
COMMENT ON COLUMN agg_accidents_by_hour.slight IS 'Slight collisions';
COMMENT ON COLUMN agg_accidents_by_hour.casualties IS 'Total casualties';
COMMENT ON COLUMN agg_accidents_by_hour.ksi_rate IS '(fatal + serious) / accidents';

CREATE TABLE agg_accidents_by_day (
	full_date DATE, 
	year INTEGER, 
	weekday_name VARCHAR(10), 
	is_weekend BOOLEAN, 
	accidents INTEGER, 
	fatal INTEGER, 
	serious INTEGER, 
	slight INTEGER, 
	casualties INTEGER, 
	ksi_rate FLOAT, 
	mean_temperature_c FLOAT, 
	mean_precipitation_mm FLOAT
);
COMMENT ON TABLE agg_accidents_by_day IS 'Daily collision counts with weather';
COMMENT ON COLUMN agg_accidents_by_day.full_date IS 'Date';
COMMENT ON COLUMN agg_accidents_by_day.year IS 'Year';
COMMENT ON COLUMN agg_accidents_by_day.weekday_name IS 'Weekday';
COMMENT ON COLUMN agg_accidents_by_day.is_weekend IS 'Weekend flag';
COMMENT ON COLUMN agg_accidents_by_day.accidents IS 'Number of collisions';
COMMENT ON COLUMN agg_accidents_by_day.fatal IS 'Fatal collisions';
COMMENT ON COLUMN agg_accidents_by_day.serious IS 'Serious collisions';
COMMENT ON COLUMN agg_accidents_by_day.slight IS 'Slight collisions';
COMMENT ON COLUMN agg_accidents_by_day.casualties IS 'Total casualties';
COMMENT ON COLUMN agg_accidents_by_day.ksi_rate IS '(fatal + serious) / accidents';
COMMENT ON COLUMN agg_accidents_by_day.mean_temperature_c IS 'Mean temperature at collision hours';
COMMENT ON COLUMN agg_accidents_by_day.mean_precipitation_mm IS 'Mean hourly precipitation at collision hours';

CREATE TABLE agg_accidents_by_road (
	first_road_class_label VARCHAR(20), 
	road_type_label VARCHAR(40), 
	speed_limit_label VARCHAR(20), 
	urban_rural_label VARCHAR(20), 
	accidents INTEGER, 
	fatal INTEGER, 
	serious INTEGER, 
	slight INTEGER, 
	casualties INTEGER, 
	ksi_rate FLOAT
);
COMMENT ON TABLE agg_accidents_by_road IS 'Collisions by road class, road type, speed limit and urban/rural';
COMMENT ON COLUMN agg_accidents_by_road.first_road_class_label IS 'Road class';
COMMENT ON COLUMN agg_accidents_by_road.road_type_label IS 'Road type';
COMMENT ON COLUMN agg_accidents_by_road.speed_limit_label IS 'Speed limit';
COMMENT ON COLUMN agg_accidents_by_road.urban_rural_label IS 'Urban/rural';
COMMENT ON COLUMN agg_accidents_by_road.accidents IS 'Number of collisions';
COMMENT ON COLUMN agg_accidents_by_road.fatal IS 'Fatal collisions';
COMMENT ON COLUMN agg_accidents_by_road.serious IS 'Serious collisions';
COMMENT ON COLUMN agg_accidents_by_road.slight IS 'Slight collisions';
COMMENT ON COLUMN agg_accidents_by_road.casualties IS 'Total casualties';
COMMENT ON COLUMN agg_accidents_by_road.ksi_rate IS '(fatal + serious) / accidents';

CREATE TABLE agg_condition_impact (
	factor VARCHAR(40), 
	level VARCHAR(60), 
	accidents INTEGER, 
	fatal INTEGER, 
	serious INTEGER, 
	slight INTEGER, 
	casualties INTEGER, 
	ksi_rate FLOAT
);
COMMENT ON TABLE agg_condition_impact IS 'Long-format table: severity profile for each level of each contributing factor';
COMMENT ON COLUMN agg_condition_impact.factor IS 'Contributing factor (weather, surface, light, ...)';
COMMENT ON COLUMN agg_condition_impact.level IS 'Factor level';
COMMENT ON COLUMN agg_condition_impact.accidents IS 'Number of collisions';
COMMENT ON COLUMN agg_condition_impact.fatal IS 'Fatal collisions';
COMMENT ON COLUMN agg_condition_impact.serious IS 'Serious collisions';
COMMENT ON COLUMN agg_condition_impact.slight IS 'Slight collisions';
COMMENT ON COLUMN agg_condition_impact.casualties IS 'Total casualties';
COMMENT ON COLUMN agg_condition_impact.ksi_rate IS '(fatal + serious) / accidents';

CREATE TABLE mart_location_hotspots (
	hotspot_id VARCHAR(24) NOT NULL, 
	hotspot_lat FLOAT, 
	hotspot_lon FLOAT, 
	accidents INTEGER, 
	fatal INTEGER, 
	serious INTEGER, 
	slight INTEGER, 
	casualties INTEGER, 
	ksi_rate FLOAT, 
	police_force_name VARCHAR(40), 
	PRIMARY KEY (hotspot_id)
);
COMMENT ON TABLE mart_location_hotspots IS 'Collision hotspots on a ~5 km grid';
COMMENT ON COLUMN mart_location_hotspots.hotspot_id IS 'Grid cell id';
COMMENT ON COLUMN mart_location_hotspots.hotspot_lat IS 'Cell centre latitude (0.05 deg grid)';
COMMENT ON COLUMN mart_location_hotspots.hotspot_lon IS 'Cell centre longitude (0.05 deg grid)';
COMMENT ON COLUMN mart_location_hotspots.accidents IS 'Number of collisions';
COMMENT ON COLUMN mart_location_hotspots.fatal IS 'Fatal collisions';
COMMENT ON COLUMN mart_location_hotspots.serious IS 'Serious collisions';
COMMENT ON COLUMN mart_location_hotspots.slight IS 'Slight collisions';
COMMENT ON COLUMN mart_location_hotspots.casualties IS 'Total casualties';
COMMENT ON COLUMN mart_location_hotspots.ksi_rate IS '(fatal + serious) / accidents';
COMMENT ON COLUMN mart_location_hotspots.police_force_name IS 'Most frequent police force in the cell';

CREATE TABLE agg_vehicle_casualty (
	vehicle_category VARCHAR(30), 
	casualty_class VARCHAR(30), 
	casualty_severity VARCHAR(10), 
	casualties INTEGER
);
COMMENT ON TABLE agg_vehicle_casualty IS 'Casualties by vehicle category, casualty class and severity';
COMMENT ON COLUMN agg_vehicle_casualty.vehicle_category IS 'Vehicle category linked to the casualty';
COMMENT ON COLUMN agg_vehicle_casualty.casualty_class IS 'Casualty class';
COMMENT ON COLUMN agg_vehicle_casualty.casualty_severity IS 'Casualty severity';
COMMENT ON COLUMN agg_vehicle_casualty.casualties IS 'Number of casualties';

CREATE TABLE ml_accident_features (
	collision_index VARCHAR(20) NOT NULL, 
	collision_datetime TIMESTAMP WITHOUT TIME ZONE, 
	year INTEGER, 
	month INTEGER, 
	weekday VARCHAR(10), 
	hour INTEGER, 
	latitude FLOAT, 
	longitude FLOAT, 
	weather_cell_id VARCHAR(16), 
	police_force VARCHAR(40), 
	nation VARCHAR(10), 
	local_authority_ons_district VARCHAR(12), 
	urban_or_rural VARCHAR(20), 
	first_road_class VARCHAR(20), 
	road_type VARCHAR(40), 
	speed_limit FLOAT, 
	junction_detail VARCHAR(40), 
	junction_control VARCHAR(40), 
	light_conditions VARCHAR(40), 
	weather_conditions VARCHAR(40), 
	road_surface_conditions VARCHAR(30), 
	special_conditions_at_site VARCHAR(40), 
	carriageway_hazards VARCHAR(40), 
	number_of_vehicles INTEGER, 
	number_of_casualties INTEGER, 
	temperature_c FLOAT, 
	precipitation_mm FLOAT, 
	snowfall_cm FLOAT, 
	wind_speed_kmh FLOAT, 
	wind_gusts_kmh FLOAT, 
	cloud_cover_pct FLOAT, 
	humidity_pct FLOAT, 
	weather_matched BOOLEAN, 
	involves_pedal_cycle BOOLEAN, 
	involves_motorcycle BOOLEAN, 
	involves_car BOOLEAN, 
	involves_bus BOOLEAN, 
	involves_goods_vehicle BOOLEAN, 
	pedestrian_involved BOOLEAN, 
	mean_driver_age FLOAT, 
	youngest_driver_age FLOAT, 
	severity INTEGER, 
	severity_label VARCHAR(10), 
	PRIMARY KEY (collision_index)
);
CREATE INDEX ix_ml_features_datetime ON ml_accident_features (collision_datetime);
COMMENT ON TABLE ml_accident_features IS 'Model-ready table for Part 2 (no post-outcome / leakage columns)';
COMMENT ON COLUMN ml_accident_features.collision_index IS 'DfT unique collision id';
COMMENT ON COLUMN ml_accident_features.collision_datetime IS 'Local date/time (used for the chronological split)';
COMMENT ON COLUMN ml_accident_features.year IS 'Year';
COMMENT ON COLUMN ml_accident_features.month IS 'Month';
COMMENT ON COLUMN ml_accident_features.weekday IS 'Weekday name';
COMMENT ON COLUMN ml_accident_features.hour IS 'Hour 0-23';
COMMENT ON COLUMN ml_accident_features.latitude IS 'Latitude';
COMMENT ON COLUMN ml_accident_features.longitude IS 'Longitude';
COMMENT ON COLUMN ml_accident_features.weather_cell_id IS 'Weather grid cell';
COMMENT ON COLUMN ml_accident_features.police_force IS 'Police force name';
COMMENT ON COLUMN ml_accident_features.nation IS 'Nation';
COMMENT ON COLUMN ml_accident_features.local_authority_ons_district IS 'ONS district code';
COMMENT ON COLUMN ml_accident_features.urban_or_rural IS 'Urban/rural';
COMMENT ON COLUMN ml_accident_features.first_road_class IS 'Road class';
COMMENT ON COLUMN ml_accident_features.road_type IS 'Road type';
COMMENT ON COLUMN ml_accident_features.speed_limit IS 'Speed limit (mph)';
COMMENT ON COLUMN ml_accident_features.junction_detail IS 'Junction type';
COMMENT ON COLUMN ml_accident_features.junction_control IS 'Junction control';
COMMENT ON COLUMN ml_accident_features.light_conditions IS 'Light conditions';
COMMENT ON COLUMN ml_accident_features.weather_conditions IS 'Police-recorded weather';
COMMENT ON COLUMN ml_accident_features.road_surface_conditions IS 'Road surface';
COMMENT ON COLUMN ml_accident_features.special_conditions_at_site IS 'Special conditions';
COMMENT ON COLUMN ml_accident_features.carriageway_hazards IS 'Carriageway hazards';
COMMENT ON COLUMN ml_accident_features.number_of_vehicles IS 'Vehicles involved';
COMMENT ON COLUMN ml_accident_features.number_of_casualties IS 'Casualties';
COMMENT ON COLUMN ml_accident_features.temperature_c IS 'Temperature (C)';
COMMENT ON COLUMN ml_accident_features.precipitation_mm IS 'Precipitation (mm/h)';
COMMENT ON COLUMN ml_accident_features.snowfall_cm IS 'Snowfall (cm/h)';
COMMENT ON COLUMN ml_accident_features.wind_speed_kmh IS 'Wind speed (km/h)';
COMMENT ON COLUMN ml_accident_features.wind_gusts_kmh IS 'Wind gusts (km/h)';
COMMENT ON COLUMN ml_accident_features.cloud_cover_pct IS 'Cloud cover (%)';
COMMENT ON COLUMN ml_accident_features.humidity_pct IS 'Relative humidity (%)';
COMMENT ON COLUMN ml_accident_features.weather_matched IS 'Measured weather available';
COMMENT ON COLUMN ml_accident_features.involves_pedal_cycle IS 'Pedal cycle involved';
COMMENT ON COLUMN ml_accident_features.involves_motorcycle IS 'Motorcycle involved';
COMMENT ON COLUMN ml_accident_features.involves_car IS 'Car involved';
COMMENT ON COLUMN ml_accident_features.involves_bus IS 'Bus involved';
COMMENT ON COLUMN ml_accident_features.involves_goods_vehicle IS 'Goods vehicle involved';
COMMENT ON COLUMN ml_accident_features.pedestrian_involved IS 'At least one pedestrian casualty';
COMMENT ON COLUMN ml_accident_features.mean_driver_age IS 'Mean driver age';
COMMENT ON COLUMN ml_accident_features.youngest_driver_age IS 'Youngest driver age';
COMMENT ON COLUMN ml_accident_features.severity IS 'TARGET: 1 Fatal, 2 Serious, 3 Slight';
COMMENT ON COLUMN ml_accident_features.severity_label IS 'TARGET label';

CREATE TABLE etl_ingestion_log (
	run_id VARCHAR(20), 
	source VARCHAR(30), 
	dataset VARCHAR(40), 
	url TEXT, 
	extracted_at_utc VARCHAR(30), 
	status VARCHAR(10), 
	http_status VARCHAR(5), 
	row_count INTEGER, 
	bytes INTEGER, 
	sha256 VARCHAR(64), 
	local_path TEXT, 
	message TEXT
);
COMMENT ON TABLE etl_ingestion_log IS 'One row per file or API extraction';
COMMENT ON COLUMN etl_ingestion_log.run_id IS 'Pipeline run id';
COMMENT ON COLUMN etl_ingestion_log.source IS 'Source system';
COMMENT ON COLUMN etl_ingestion_log.dataset IS 'Dataset / file';
COMMENT ON COLUMN etl_ingestion_log.url IS 'Source URL';
COMMENT ON COLUMN etl_ingestion_log.extracted_at_utc IS 'Extraction timestamp (UTC)';
COMMENT ON COLUMN etl_ingestion_log.status IS 'SUCCESS / CACHED / FAILED / SKIPPED';
COMMENT ON COLUMN etl_ingestion_log.http_status IS 'HTTP status code';
COMMENT ON COLUMN etl_ingestion_log.row_count IS 'Rows in the extracted file';
COMMENT ON COLUMN etl_ingestion_log.bytes IS 'File size';
COMMENT ON COLUMN etl_ingestion_log.sha256 IS 'File checksum';
COMMENT ON COLUMN etl_ingestion_log.local_path IS 'Raw landing-zone path';
COMMENT ON COLUMN etl_ingestion_log.message IS 'Details / error';

CREATE TABLE etl_run_log (
	run_id VARCHAR(20), 
	step VARCHAR(30), 
	status VARCHAR(10), 
	started_at_utc VARCHAR(30), 
	finished_at_utc VARCHAR(30), 
	duration_s FLOAT, 
	rows_in INTEGER, 
	rows_out INTEGER, 
	message TEXT
);
COMMENT ON TABLE etl_run_log IS 'One row per pipeline step execution';
COMMENT ON COLUMN etl_run_log.run_id IS 'Pipeline run id';
COMMENT ON COLUMN etl_run_log.step IS 'Pipeline step';
COMMENT ON COLUMN etl_run_log.status IS 'SUCCESS / FAILED';
COMMENT ON COLUMN etl_run_log.started_at_utc IS 'Start';
COMMENT ON COLUMN etl_run_log.finished_at_utc IS 'End';
COMMENT ON COLUMN etl_run_log.duration_s IS 'Duration (s)';
COMMENT ON COLUMN etl_run_log.rows_in IS 'Rows read';
COMMENT ON COLUMN etl_run_log.rows_out IS 'Rows written';
COMMENT ON COLUMN etl_run_log.message IS 'Details';

CREATE TABLE dq_rejected_records (
	run_id VARCHAR(20), 
	table_name VARCHAR(20), 
	record_id VARCHAR(60), 
	rule_id VARCHAR(6), 
	action VARCHAR(8), 
	field VARCHAR(40), 
	value TEXT, 
	description TEXT, 
	source_file TEXT
);
CREATE INDEX ix_dq_rejected_run ON dq_rejected_records (run_id);
COMMENT ON TABLE dq_rejected_records IS 'Rejected-record / error log produced by the data-quality step';
COMMENT ON COLUMN dq_rejected_records.run_id IS 'Pipeline run id';
COMMENT ON COLUMN dq_rejected_records.table_name IS 'Table the record belongs to';
COMMENT ON COLUMN dq_rejected_records.record_id IS 'Business key of the record';
COMMENT ON COLUMN dq_rejected_records.rule_id IS 'Validation rule id';
COMMENT ON COLUMN dq_rejected_records.action IS 'REJECT (row removed) or NULLIFY (value set to null)';
COMMENT ON COLUMN dq_rejected_records.field IS 'Offending field';
COMMENT ON COLUMN dq_rejected_records.value IS 'Offending value';
COMMENT ON COLUMN dq_rejected_records.description IS 'Rule description';
COMMENT ON COLUMN dq_rejected_records.source_file IS 'Raw file the record came from';

-- Spatial columns added after each load (see traffic_pipeline/load.py):
ALTER TABLE fact_accident ADD COLUMN IF NOT EXISTS geom geometry(Point, 4326);
CREATE INDEX IF NOT EXISTS ix_fact_accident_geom ON fact_accident USING GIST (geom);
ALTER TABLE mart_location_hotspots ADD COLUMN IF NOT EXISTS geom geometry(Point, 4326);
